export const standardCategories = [
    "Auto Insurance",
    "Auto Repairs",
    "Auto/Maintenance",
    "Bank Fees",
    "Car Payment",
    "Childcare",
    "Clothing",
    "Debt Payments",
    "Dining Out",
    "Education",
    "Entertainment",
    "Gas",
    "Gifts & Donations",
    "Groceries",
    "Health & Fitness",
    "Home Insurance",
    "Housing Repairs",
    "Internet",
    "Investments",
    "Life Insurance",
    "Medications",
    "Miscellaneous",
    "Mortgage/Rent",
    "Personal Care",
    "Pet",
    "Phone",
    "Public Transit",
    "Registration & Fees",
    "Subscriptions",
    "Taxes",
    "Utilities",
    "Gas/Electricity",
]